services:
  actual-budget:
    image: actualbudget/actual-server:latest
    container_name: actual-budget
    restart: unless-stopped
    volumes:
      - actual-budget_data:/data
    networks:
      - ragnalab-net
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual-budget.rule=Host(`budget.${DOMAIN}`)"
      - "traefik.http.routers.actual-budget.entrypoints=websecure"
      - "traefik.http.routers.actual-budget.tls.certresolver=cloudflare"
      - "traefik.http.services.actual-budget.loadbalancer.server.port=5006"
      - "homepage.group=Management"
      - "homepage.name=Actual Budget"
      - "homepage.icon=actual-budget"
      - "homepage.href=https://budget.${DOMAIN}"
      - "homepage.description=Budget management"
      - "kuma.actual-budget.http.name=Actual Budget"
      - "kuma.actual-budget.http.url=https://budget.${DOMAIN}"
volumes:
  actual-budget_data:
    name: actual-budget_data