http:
  routers:
    homeassistant:
      rule: "Host(`hass.ragnalab.xyz`)"
      tls:
        certResolver: cloudflare
      entryPoints:
        - websecure
      service: homeassistant

  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://172.22.0.1:8123"


