# proxy/traefik.yml - Traefik Static Configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 10000

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: ragnalab-net
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

api:
  dashboard: true
  insecure: false

certificatesResolvers:
  cloudflare:
    acme:
      email: rushil.basappa@gmail.com
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
