services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - ragnalab-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=cloudflare"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "homepage.group=Management"
      - "homepage.name=Whoami"
      - "homepage.icon=hashicorp-consul"
      - "homepage.href=https://whoami.${DOMAIN}"
      - "homepage.description=Whoami"
      - "kuma.whoami.http.name=Whoami"
      - "kuma.whoami.http.url=https://whoami.${DOMAIN}"
