services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbs
    restart: unless-stopped
    command: hbbs -r ${DEVICE_HOST}:21117
    volumes:
      - rustdesk_data:/data
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21118:21118"
      - "21119:21119"
    depends_on:
      - hbbr

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    restart: unless-stopped
    command: hbbr
    volumes:
      - rustdesk_data:/data
    ports:
      - "21117:21117"

volumes:
  rustdesk_data:
    name: rustdesk_data