services:
  tandoor:
    image: vabene1111/recipes:latest
    container_name: tandoor
    restart: unless-stopped
    depends_on:
      - traefik
      - postgres-main
    environment:
      - SECRET_KEY=safehaven
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${TANDOOR_POSTGRES_DB}
      - POSTGRES_USER=${TANDOOR_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TANDOOR_POSTGRES_PASSWORD}
      - ALLOWED_HOSTS=recipes.${DOMAIN}
      - TZ=${TIMEZONE}
      - REVERSE_PROXY=true
    volumes:
      - tandoor_mediafiles:/opt/recipes/mediafiles
      - tandoor_staticfiles:/opt/recipes/staticfiles
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tandoor.rule=Host(`recipes.${DOMAIN}`)"
      - "traefik.http.routers.tandoor.entrypoints=websecure"
      - "traefik.http.routers.tandoor.tls.certresolver=cloudflare"
      - "traefik.http.services.tandoor.loadbalancer.server.port=8080"
      - "homepage.group=Media"
      - "homepage.name=Tandoor Recipes"
      - "homepage.icon=tandoor-recipes"
      - "homepage.href=https://recipes.${DOMAIN}"
      - "homepage.description=Self-hosted recipe manager"
      - "kuma.tandoor.http.name=Tandoor Recipes"
      - "kuma.tandoor.http.url=https://recipes.${DOMAIN}"
    networks:
      - ragnalab-net
      - postgres-internal

volumes:
  tandoor_mediafiles:
    name: tandoor_mediafiles
  tandoor_staticfiles:
    name: tandoor_staticfiles
